apiVersion: apps/v1
kind: Deployment
metadata:
  name: flavor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flavor
  template:
    metadata:
      labels:
        app: flavor
    spec:
      containers:
      - image: okteto.dev/flavor:latest
        name: flavor
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "f89b76e5-1334-48f2-be64-dca1ce71847a"
        - name: Vless_Path
          value: "/appl"
        - name: Vmess_UUID
          value: "f89b76e5-1334-48f2-be64-dca1ce71847a"
        - name: Vmess_Path
          value: "/addm"
        - name: Share_Path
          value: "/together"
